
name: build
on: [push]
jobs:
  macos-metal:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls
          cd examples
          ls
          ../pmbuild mac -libs