
name: build
on: [push]
jobs:
  macos-metal:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: "recursive"
          lfs: true
      - run: .ci/mac-metal.sh
  macos-gl:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: "recursive"
          lfs: true
      - run: .ci/mac-gl.sh
  linux-gl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: "recursive"
          lfs: true
      - run: |
        sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r"
        sudo apt-get install libglew-dev
        .ci/linux-gl.sh