
name: build
on: [push]
jobs:
  macos-metal:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
          lfs: true
      - run: .ci/mac-metal.sh
  macos-gl:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
          lfs: true
      - run: .ci/mac-gl.sh
  linux-gl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          submodules: true
          lfs: true
      - run: .ci/linux-gl.sh