
{
	chain: [blit_depth, bloom, colour_lut, blit_post_process],
	parameters: 
	{
		high_pass: 
		{
			threshold: [0.753000],
		},
		colour_lut: 
		{
			textures: 
			{
				lookup_texture: 
				{
					filename: data/textures/luts/sepia.dds,
					sampler_state: 4195589,
				},
			},
		},
	},
}