{
	blend_states:
	{
		disabled:
		{
			blend_enable: false,	
		}
		
		additive:
		{
			blend_enable: true,
			src_blend: one,
			dest_blend: one
		}
		
		alpha_belnd:
		{
			blend_enable: true,
			src_blend: src_alpha,
			dest_blend: inv_src_alpha
		}
	},
	
	sampler_states:
	{
		wrap_linear:
		{
			filter: linear,
			address: wrap
		},
	},
	
	depth_stencil_states:
	{
		disabled:
		{
			depth_enable: false,
		},
		
		default:
		{
			depth_enable: true,
			depth_write: true,
			depth_func: "less"
		},
		
		depth_never:
		{
			depth_enable: true,
			depth_write: true,
			depth_func: "never"
		},
		
		stencil_test:
		{
			depth_enable: true,
			depth_write: true,
			depth_func: "always",
			stencil_enable: true,
			stencil_write_mask: 0xff,
			stencil_read_mask: 0xff,
			
			stencil_op:
			{
				stencil_fail: "keep",
				depth_fail: "keep",
				stencil_pass: "replace",
				stencil_func: "equal"
			}
		},
	},
	
	raster_states:
	{
		default:
		{
			cull_mode: back,
		},
		
		reversed:
		{
			cull_mode: front,
		},
		
		shadow_map:
		{
			cull_mode: front,
		},
		
		wireframe:
		{
			cull_mode: none,
			fill_mode: wireframe
		}
		
		front_face_cull:
		{
			cull_mode: front,
			fill_mode: solid
		}
	},
	
	render_targets:
	{
		shadow_map:
		{
			size: [2048,2048],
			format: d24s8,
		},
	},
				
	views:
	{
		single_shadow_view:
		{
			target:[shadow_map],
			clear_depth: 1.0,
			colour_write_mask: 0xf,
			blend_state: disabled,
			viewport: [0.0, 0.0, 1.0, 1.0],
			raster_state: reversed,
			depth_stencil_state: default,
			pmfx_shader: forward_render,
			technique: zonly,
			scene: main_scene,
			camera: shadow_camera,
			scene_views:["ces_render_scene"],
			render_flags:["forward_lit"]
		},
		
		main_view:
		{
			target:[main_colour, main_depth],
			clear_colour:[0.5, 0.5, 0.5, 1.0],
			clear_depth: 1.0,
			colour_write_mask: 0xf,
			blend_state: disabled,
			viewport: [0.0, 0.0, 1.0, 1.0],
			raster_state: default,
			depth_stencil_state: default,
			pmfx_shader: forward_render,
			technique: forward_lit,
			scene: main_scene,
			camera: model_viewer_camera,
			scene_views:["ces_render_scene"],
			render_flags:["forward_lit"],
			
			sampler_bindings:
			[
				{ texture: shadow_map, unit: 15, state: wrap_linear, shader: ps },
			],
		},
		
		editor_view:
		{
			target:[main_colour, main_depth],
			colour_write_mask: 0xf,
			blend_state: disabled,
			viewport: [0.0, 0.0, 1.0, 1.0],
			raster_state: wireframe,
			depth_stencil_state: default,
			pmfx_shader: forward_render,
			technique: constant_colour,
			scene: main_scene,
			camera: model_viewer_camera,
			scene_views:["ces_render_editor"]
		},
		
		debug_view:
		{
			target:[main_colour, main_depth],
			colour_write_mask: 0xf,
			blend_state: disabled,
			viewport: [0.0, 0.0, 1.0, 1.0],
			raster_state: wireframe,
			depth_stencil_state: default,
			pmfx_shader: forward_render,
			technique: constant_colour,
			scene: main_scene,
			camera: model_viewer_camera,
			scene_views:["shadows_debug"]
		},
	},
}